# Generated by Django 4.1.5 on 2023-02-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='product_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
